name: Deploy to Hugging Face
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Install git-lfs
        run: |
          git lfs install

      - name: Debug Environment Variables
        run: |
          echo "HF_USERNAME: $HF_USERNAME"
          echo "HF_SPACE_NAME: $HF_SPACE_NAME"
          echo "HF_TOKEN: ${HF_TOKEN:0:4}***" # Masked token for security

      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Add Hugging Face Space remote
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ vars.HF_USERNAME || 'noir1112' }}
          HF_SPACE_NAME: ${{ vars.HF_SPACE_NAME || 'GitLens' }}
        run: |
          git remote remove space || true
          git remote add space https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$HF_SPACE_NAME

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ vars.HF_USERNAME || 'noir1112' }}
          HF_SPACE_NAME: ${{ vars.HF_SPACE_NAME || 'GitLens' }}
        run: |
          echo "Pushing to Hugging Face Spaces..."
          git push space main