name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Push to Hugging Face Spaces
        uses: huggingface/huggingface-push-space@main
        with:
          space_id: ${{ secrets.HF_SPACE_ID }}
          space_type: gradio
          branch: main
          folder: .
          hf_token: ${{ secrets.HF_TOKEN }}